name: Build IDE

on: [push]

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        build: ["-win", "-linux", "-mac"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk+fx # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Install JPPM
      run: wget -O - https://github.com/jphp-group/jphp/releases/download/jppm-0.6.6/jppm-setup-0.6.6.sh | bash
    - name: Prepare IDE
      run: jppm prepare-ide ${{ matrix.build }}
    - name: Build IDE
      run: jppm build-ide ${{ matrix.build }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: DevelNext${{ matrix.build }}
        # Directory containing files to upload
        path: ./ide/build

